In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("claim_data.csv")
df

,Claim ID,Provider ID,Patient ID,Date of Service,Billed Amount,Procedure Code,Diagnosis Code,Allowed Amount,Paid Amount,Insurance Type,Claim Status,Reason Code,Follow-up Required,AR Status,Outcome
0,0HO1FSN4AP,126528997,7936697103,08/07/2024,304,99231,A02.1,218,203,Self-Pay,Paid,Incorrect billing information,Yes,Pending,Partially Paid
1,9U86CI2P5A,6986719948,1547160031,06/21/2024,348,99213,A16.5,216,206,Medicare,Paid,Pre-existing condition,Yes,Open,Denied
2,1QEU1AIDAU,1355108115,2611585318,07/04/2024,235,99213,A00.1,148,119,Commercial,Under Review,Duplicate claim,No,Denied,Denied
3,WH7XDS8CEO,9991055906,7167948632,05/26/2024,112,99215,A18.6,79,69,Medicare,Denied,Authorization not obtained,No,Partially Paid,Denied
4,M6OJEZ8KGI,7382167012,2140226267,07/16/2024,406,99238,A17.9,320,259,Medicare,Denied,Authorization not obtained,No,On Hold,Denied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0B0TP89BQF,7640195037,6836887959,05/30/2024,307,99238,A08.8,231,213,Commercial,Paid,Service not covered,No,Pending,Partially Paid
996,VVROAPZFFA,3378390045,8592277150,06/23/2024,150,99215,A02.8,105,99,Medicare,Paid,Lack of medical necessity,Yes,Closed,Partially Paid
997,Q9J55DIMLR,2766789913,9757787667,07/07/2024,128,99213,A02.2,83,75,Medicare,Paid,Authorization not obtained,Yes,Partially Paid,Paid
998,531HVTDM18,1335890669,1995402912,05/14/2024,178,99215,A08.2,122,103,Medicaid,Under Review,Patient eligibility issues,Yes,On Hold,Denied
999,VGRS6DLO92,4717110849,5523750626,09/07/2024,143,99233,A05.3,110,101,Self-Pay,Paid,Missing documentation,No,On Hold,Denied

In [5]:
df.columns

Index(['Claim ID', 'Provider ID', 'Patient ID', 'Date of Service',
       'Billed Amount', 'Procedure Code', 'Diagnosis Code', 'Allowed Amount',
       'Paid Amount', 'Insurance Type', 'Claim Status', 'Reason Code',
       'Follow-up Required', 'AR Status', 'Outcome'],
      dtype='object')

In [19]:
df.drop(['Reason Code','Diagnosis Code','Claim ID'], inplace=True, axis=1)

In [20]:
df.head()

,Provider ID,Patient ID,Date of Service,Billed Amount,Procedure Code,Allowed Amount,Paid Amount,Insurance Type,Claim Status,Follow-up Required,AR Status,Outcome
0,126528997,7936697103,08/07/2024,304,99231,218,203,Self-Pay,Paid,Yes,Pending,Partially Paid
1,6986719948,1547160031,06/21/2024,348,99213,216,206,Medicare,Paid,Yes,Open,Denied
2,1355108115,2611585318,07/04/2024,235,99213,148,119,Commercial,Under Review,No,Denied,Denied
3,9991055906,7167948632,05/26/2024,112,99215,79,69,Medicare,Denied,No,Partially Paid,Denied
4,7382167012,2140226267,07/16/2024,406,99238,320,259,Medicare,Denied,No,On Hold,Denied

In [7]:
df.describe()

,Provider ID,Patient ID,Billed Amount,Procedure Code,Allowed Amount,Paid Amount
count,1.000000e+03,1.000000e+03,1000.00000,1000.000000,1000.000000,1000.000000
mean,4.909473e+09,5.112327e+09,297.19100,99223.969000,223.112000,200.754000
std,2.866473e+09,2.919255e+09,116.36365,8.390736,90.784731,83.353688
min,5.364682e+06,9.455298e+06,100.00000,99213.000000,64.000000,53.000000
25%,2.460360e+09,2.600572e+09,197.00000,99215.000000,147.750000,133.000000
50%,5.002762e+09,5.216802e+09,297.00000,99222.000000,225.000000,200.000000
75%,7.313899e+09,7.753702e+09,395.00000,99232.000000,289.000000,262.000000
max,9.991056e+09,9.964057e+09,500.00000,99238.000000,442.000000,423.000000

In [16]:
df.duplicated().sum()

0

In [17]:
df.head()

,Claim ID,Provider ID,Patient ID,Date of Service,Billed Amount,Procedure Code,Diagnosis Code,Allowed Amount,Paid Amount,Insurance Type,Claim Status,Reason Code,Follow-up Required,AR Status,Outcome
0,0HO1FSN4AP,126528997,7936697103,08/07/2024,304,99231,A02.1,218,203,Self-Pay,Paid,Incorrect billing information,Yes,Pending,Partially Paid
1,9U86CI2P5A,6986719948,1547160031,06/21/2024,348,99213,A16.5,216,206,Medicare,Paid,Pre-existing condition,Yes,Open,Denied
2,1QEU1AIDAU,1355108115,2611585318,07/04/2024,235,99213,A00.1,148,119,Commercial,Under Review,Duplicate claim,No,Denied,Denied
3,WH7XDS8CEO,9991055906,7167948632,05/26/2024,112,99215,A18.6,79,69,Medicare,Denied,Authorization not obtained,No,Partially Paid,Denied
4,M6OJEZ8KGI,7382167012,2140226267,07/16/2024,406,99238,A17.9,320,259,Medicare,Denied,Authorization not obtained,No,On Hold,Denied

In [21]:
df.isnull().sum()

Provider ID           0
Patient ID            0
Date of Service       0
Billed Amount         0
Procedure Code        0
Allowed Amount        0
Paid Amount           0
Insurance Type        0
Claim Status          0
Follow-up Required    0
AR Status             0
Outcome               0
dtype: int64

In [22]:
df.to_csv("Healthcare.csv", index = False)

In [23]:
df1 = pd.read_csv('Healthcare.csv')
df1

,Provider ID,Patient ID,Date of Service,Billed Amount,Procedure Code,Allowed Amount,Paid Amount,Insurance Type,Claim Status,Follow-up Required,AR Status,Outcome
0,126528997,7936697103,08/07/2024,304,99231,218,203,Self-Pay,Paid,Yes,Pending,Partially Paid
1,6986719948,1547160031,06/21/2024,348,99213,216,206,Medicare,Paid,Yes,Open,Denied
2,1355108115,2611585318,07/04/2024,235,99213,148,119,Commercial,Under Review,No,Denied,Denied
3,9991055906,7167948632,05/26/2024,112,99215,79,69,Medicare,Denied,No,Partially Paid,Denied
4,7382167012,2140226267,07/16/2024,406,99238,320,259,Medicare,Denied,No,On Hold,Denied
...,...,...,...,...,...,...,...,...,...,...,...,...
995,7640195037,6836887959,05/30/2024,307,99238,231,213,Commercial,Paid,No,Pending,Partially Paid
996,3378390045,8592277150,06/23/2024,150,99215,105,99,Medicare,Paid,Yes,Closed,Partially Paid
997,2766789913,9757787667,07/07/2024,128,99213,83,75,Medicare,Paid,Yes,Partially Paid,Paid
998,1335890669,1995402912,05/14/2024,178,99215,122,103,Medicaid,Under Review,Yes,On Hold,Denied
999,4717110849,5523750626,09/07/2024,143,99233,110,101,Self-Pay,Paid,No,On Hold,Denied

# ANALYSIS IN SQL

1. Find the Distinct values of procudre code?

2. Find the Distinct values of Insurance type using group by?

3. Find the Distinct values of Claim status using group by?

4. Find the Distinct values of Outcome count using group by?

5. Find the Distinct values of AR_status using group by?

6. Find the total posted in month of August?

7. Find the total posted in month of September?

1. Find the Distinct values of procudre code?

SELECT DISTINCT Procedure_Code, COUNT(*) AS Procedure_Code_count
FROM Healthcare
GROUP BY Procedure_Code;

2. Find the Distinct values of Insurance type using group by?

select distinct Insurance_Type, count(*)as Insurance_Type_Count from Healthcare group by Insurance_Type

3. Find the Distinct values of Claim status using group by?

select distinct Claim_Status, count(*)as Claim_Status_count from Healthcare group by Claim_Status

4. Find the Distinct values of Outcome count using group by?

select distinct Outcome, count(*)as Outcome_count from Healthcare group by Outcome

5. Find the Distinct values of AR_status using group by?

select distinct AR_Status, count(*)as AR_Status_count from Healthcare group by AR_Status

6. Find the total posted in month of August?

SELECT sum(Paid_Amount)as Aug_month_paid
FROM Healthcare
WHERE Date_of_Service between '2024-08-01' and '2024-08-30' ;

7. Find the total posted in month of September?

SELECT sum(Paid_Amount)as sep_month_paid
FROM Healthcare
WHERE Date_of_Service between '2024-09-01' and '2024-09-30' ;